import Head from 'next/head'
import { SiteNav, SiteFooter } from '../components/Layout'

export default function Terms() {
  return (
    <>
      <Head>
        <title>Terms of Use — RhymeItNow</title>
        <meta name="description" content="Terms of use for RhymeItNow.com" />
      </Head>
      <SiteNav />
      <main style={{ maxWidth: '680px', margin: '0 auto', padding: '3rem 1.5rem', fontSize: '0.95rem', lineHeight: '1.8', color: '#8a7a5a' }}>
        <h1 style={{ fontSize: '1.8rem', fontWeight: '700', color: '#f0e4c8', marginBottom: '0.5rem' }}>Terms of Use</h1>
        <p style={{ color: '#4a4030', marginBottom: '2rem', fontSize: '0.85rem' }}>Last updated: January 2025</p>

        {[
          ['Acceptance of Terms', 'By accessing and using RhymeItNow.com, you accept and agree to be bound by these Terms of Use. If you do not agree to these terms, please do not use our site.'],
          ['Use of the Service', 'RhymeItNow provides a free AI-powered rhyme finding tool for personal and commercial creative use. You may use our rhyme results freely in your creative work including songs, poems, and written content.'],
          ['Prohibited Uses', 'You may not use RhymeItNow to generate content for spam, harassment, or illegal purposes. You may not attempt to reverse engineer, scrape excessively, or overload our systems. Automated bulk queries are not permitted without prior permission.'],
          ['Intellectual Property', 'The RhymeItNow name, logo, and site design are our intellectual property. Rhyme results generated by the tool are not copyrightable and may be freely used in your creative work.'],
          ['Disclaimer of Warranties', 'RhymeItNow is provided "as is" without warranties of any kind. We do not guarantee the accuracy, completeness, or availability of the service at all times.'],
          ['Limitation of Liability', 'RhymeItNow shall not be liable for any indirect, incidental, or consequential damages arising from your use of the service.'],
          ['Changes to Terms', 'We reserve the right to modify these terms at any time. Continued use of the site after changes constitutes acceptance of the new terms.'],
          ['Contact', 'For questions about these Terms of Use, please contact us through our Contact page.'],
        ].map(([title, text]) => (
          <div key={title} style={{ marginBottom: '1.75rem' }}>
            <h2 style={{ fontSize: '1.1rem', color: '#c8b890', fontWeight: '700', marginBottom: '0.5rem' }}>{title}</h2>
            <p>{text}</p>
          </div>
        ))}
      </main>
      <SiteFooter />
    </>
  )
}
